name: .NET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.100

    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{ secrets.REGISTRY_TOKEN }}/g' .nuget.config > nuget.config

    - name: Test with dotnet
      run: dotnet test --configuration Release -v:m | grep -v 'NAME_UNKNOWN:Package'

    - name: Push nuget
      run: dotnet nuget push `pwd`/InterlockLedger.Rest.Client/bin/Release/InterlockLedger.Rest.Client.*.nupkg -s https://nuget.pkg.github.com/interlockledger/index.json --skip-duplicate
