name: .NET Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{ secrets.RegistryToken }}/g' .nuget.config > nuget.config

    - name: Build with dotnet
      run: dotnet build --configuration Release -v:m | grep -v 'NAME_UNKNOWN:Package'

    - name: Pack nuget
      run: dotnet pack -o `pwd`/.nugets --configuration Release --no-build -v:m

    - name: Push nuget
      run: dotnet nuget push `pwd`/.nugets/*.nupkg -s GitHub --skip-duplicate
